### ISSUE TITLE
Deploy to diversity.buffer.com

### ISSUE THREAD

**Issue by jwinternheimer** [bufferapp/diversity-dashboard#1] opened 2018-07-17 20:01 UTC
Hey there @davidgasquez and @michael-erasmus! 👋 

Thanks again for helping out with this. I pulled the [rocker/shiny](https://hub.docker.com/r/rocker/shiny/) image instead of the `rocker/tidyverse` one for this -- everything seems to be working properly for me when I run the app locally! 😄 

Please let me know if there's anything at all I can help out with here. I really appreciate your help! 🌮

**Comment by davidgasquez** [comment] 2018-07-20 09:11
Hey there @jwinternheimer! 

I copied the configuration we had in the segmenter and deployed the dashboard at [`35.241.63.21`](http://35.241.63.21/). 

Sadly, the app times out too :cry:. I think we'll need to place these apps behind a reverse proxy like Nginx. I'll need to explore this option further! :mag:

**Comment by jwinternheimer** [comment] 2018-07-20 12:45
Hey @davidgasquez, thanks so much for that! Aw dang, that's a bummer about the app timing out. 

I can ask some folks in the R community for help. Do you happen to have logs I could share with them? Thanks again so much for helping out!

**Comment by davidgasquez** [comment] 2018-07-23 10:56
Sharing this issue with the R community might be useful! 

To be honest, I haven't been able to find logs that share anything about the issue as running the dashboard remotely returns the same logs that locally. 

Perhaps you could point them to the issues we've previously shared or share a screenshot of what's happening? 

Happy to dig more for the logs if needed!

**Comment by jwinternheimer** [comment] 2018-07-25 17:30
Got an interesting answer that shared these docs! http://docs.rstudio.com/shiny-server/#application-timeouts

**Comment by erickhun** [comment] 2018-08-09 14:15
@jwinternheimer @davidgasquez Maybe that could work ? https://github.com/virtualstaticvoid/heroku-buildpack-r/issues/97#issuecomment-354934433

**Comment by davidgasquez** [comment] 2018-08-13 12:57
I've added the code to the `dashboard.Rmd` file but seems that doesn't work. :thinking:

I've [also added it as a standalone file](https://github.com/rstudio/flexdashboard/issues/48) without much success.  

I think we'll need to write some custom Javascript since this one is for Shiny. @erickhun, would you mind if I pick your brain around this sometime this week?

**Comment by jwinternheimer** [comment] 2018-08-13 15:11
Thanks for helping out @erickhun and @davidgasquez! If this proves too difficult, I can rewrite the dashboard and use Shiny instead of Flexdashboard when I get back from vacation 😎

**Comment by michael-erasmus** [comment] 2018-08-29 02:01
Hey Julian! I got some good news, I think I finally managed to get everything working the latest Shiny app you did and got it deployed without the 'greying-out' issue.

The app is now running at: https://diversity.buffer.com

It turns out the main issue was caused by the way we we're running the app in the Dockerfile.

After looking at some examples, I realized that we're [running the app from R directly](https://github.com/bufferapp/diversity-dashboard/blob/2a4b23fc6831d7649c5e6049fc632a5a4ff085f6/Dockerfile#L19) instead of using `shiny-server`, which I suspected might be what's causing the issue.

I modified the `Dockerfile` to run `shiny-server` instead and serve the app from the `/srv/shiny-server` directory in this commit https://github.com/bufferapp/diversity-dashboard/commit/fe8003e097be33a2e3f84f416284562840ee8c83

One added benefit is that we'll also not have logs in place in the `/var/log/shiny-server` directory.

I then tested that image in K8s quickly and it seems to have fixed the issue with the app greying out!

I also took the opportunity to simplify the deployment with some of the learnings from @davidgasquez in this [PR](https://github.com/bufferapp/buda-dbt/pull/126), so the app can be deployed using Cloud Build. 

I wasn't able to get the Github integration working since I think I might need admin access to the repo, but I think that should be pretty easy to add, and then we should be able to deploy by just pushing a new version to the master branch (@davidgasquez do you perhaps have admin permissions on the repo? if so could you perhaps help us set that up, or just make me an admin?)

I also set things up so that we can use SSL by default like we did on suspender.buffer.com. 

After all of that I was able to deploy the service to Apollo and then point cloudflare to use the subdomain. 

So far it seems to be working great, so I'm closing the issue for now :smile:

**Closed by michael-erasmus** 2018-08-29 02:01 UTC
Labels: help wanted

**Comment by davidgasquez** [comment] 2018-08-29 13:33
Thanks for jumping in @michael-erasmus! 

> After looking at some examples, I realized that we're running the app from R directly instead of using shiny-server, which I suspected might be what's causing the issue.

Awesome! That was the main reason to use straight Shiny instead of Flexdashboard. :smile: 

> I wasn't able to get the Github integration working since I think I might need admin access to the repo, but I think that should be pretty easy to add, and then we should be able to deploy by just pushing a new version to the master branch (@davidgasquez do you perhaps have admin permissions on the repo? if so could you perhaps help us set that up, or just make me an admin?)

Sure! I'll make you a repository owner although we might still need to chat with Colin or José to activate the Github App in this repository.

----

Thanks again for taking care of this tricky one! Would love to hear a bit more of the technical details (_I see a reverse proxy in Apollo_) in our next chat. :smile:
